export var inputval = document.querySelector('#cityinput')
export var btn = document.querySelector('#add')
export var city = document.querySelector('#cityoutput')
export var descrip = document.querySelector('#description')
export var temp = document.querySelector('#temp')
export var wind = document.querySelector('#wind')
